spring:
  application:
    name: swaply-product-service

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:8881"

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    com.example.sagaproduct.consumer: debug